# -*- coding: utf-8 -*-
"""Analise_Dateset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qffFzd7mE-MeKAdSkCNJWXb1r_04ljM8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

url = "https://raw.githubusercontent.com/Gabriel-Chaves0/Analise_data_set/main/Cidades_brasil.csv"

data_set = pd.read_csv(url, encoding='utf-8', skiprows=3)
data_set

regioes_brasil = {
    'AC': 'Norte', 'AL': 'Nordeste', 'AP': 'Norte', 'AM': 'Norte', 'BA': 'Nordeste', 'CE': 'Nordeste',
    'DF': 'Centro-Oeste', 'ES': 'Sudeste', 'GO': 'Centro-Oeste', 'MA': 'Nordeste', 'MT': 'Centro-Oeste',
    'MS': 'Centro-Oeste', 'MG': 'Sudeste', 'PA': 'Norte', 'PB': 'Nordeste', 'PR': 'Sul', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RJ': 'Sudeste', 'RN': 'Nordeste', 'RS': 'Sul', 'RO': 'Norte', 'RR': 'Norte',
    'SC': 'Sul', 'SP': 'Sudeste', 'SE': 'Nordeste', 'TO': 'Norte'
}

"""## Tratamento de dados"""

data_set.isnull().sum()

idhm_mean_by_state = data_set.groupby('Estado')['IDHM'].mean().reset_index()
idhm_education_mean_by_state = data_set.groupby('Estado')['IDHM_Educacao'].mean().reset_index()
idhm_mean_by_state

media_educ = idhm_education_mean_by_state.set_index('Estado')['IDHM_Educacao'].to_dict()
media = idhm_mean_by_state.set_index('Estado')['IDHM'].to_dict()

data_set['IDHM_Educacao'] = data_set['IDHM_Educacao'].fillna(data_set['Estado'].map(media_educ))
data_set['IDHM'] = data_set['IDHM'].fillna(data_set['Estado'].map(media))

data_set.head(10)

"""## Questão A


"""

primeiro_quartil_idhm = data_set['IDHM'].quantile(0.25)
primeiro_quartil_idhm

"""## Questão B"""

municipios_quartil_inferior = data_set[data_set['IDHM'] < primeiro_quartil_idhm]
contagem_municipios_por_estado = municipios_quartil_inferior['Estado'].value_counts()
contagem_municipios_por_estado

municipios_totais = contagem_municipios_por_estado.sum()
top_estados = contagem_municipios_por_estado[contagem_municipios_por_estado.cumsum() <= 0.8 * municipios_totais]

"""Ao aplicar o princípio de Pareto (80/20) à distribuição de municípios com IDHM abaixo do primeiro quartil,
observamos que a maior concentração de municípios está localizada em alguns estados específicos, como Bahia (BA),
Piauí (PI) e Maranhão (MA). Esses estados apresentam uma grande parte dos municípios com menor desenvolvimento humano,
representando mais de 80% dos municípios abaixo desse quartil. Isso demonstra uma forte concentração de municípios
com baixos índices de desenvolvimento em poucas regiões do Brasil,
sugerindo um foco regional para políticas públicas voltadas à melhoria do IDHM.
"""

plt.figure(figsize=(10,6))
sns.barplot(x=top_estados.index, y=top_estados.values, palette='Blues_d')
plt.title('Top Estados com maior concentração de Municípios com IDHM menor que o 1º Quartil')
plt.xlabel('Estado')
plt.ylabel('Número de Municípios')
plt.xticks(rotation=45)
plt.show()

# Visualização do gráfico de todos os estados
plt.figure(figsize=(10,6))
sns.barplot(x=contagem_municipios_por_estado.index, y=contagem_municipios_por_estado.values, palette='Oranges_r')
plt.title('Distribuição de Municípios com IDHM menor que o 1º Quartil por Estado')
plt.xlabel('Estado')
plt.ylabel('Número de Municípios')
plt.xticks(rotation=45)
plt.show()

"""## Questão C"""

def classificar_idhm(idhm):
    if idhm < 0.550:
        return 'Baixo'
    elif 0.550 <= idhm < 0.700:
        return 'Médio'
    elif 0.700 <= idhm < 0.800:
        return 'Alto'
    else:
        return 'Muito Alto'

media_idhm_brasil = data_set['IDHM'].mean()
media_idhm_por_estado = data_set.groupby('Estado')['IDHM'].mean()

data_set['Classificacao_ONU'] = data_set['IDHM'].apply(classificar_idhm)

print(f"Média do IDHM no Brasil: {media_idhm_brasil:.3f}")

print("\nMédia do IDHM por Estado:")
print(media_idhm_por_estado)

plt.figure(figsize=(10,6))
sns.barplot(x=media_idhm_por_estado.index, y=media_idhm_por_estado.values, palette='coolwarm')
plt.title('Média do IDHM por Estado')
plt.xlabel('Estado')
plt.ylabel('Média do IDHM')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,6))
sns.countplot(x='Estado', hue='Classificacao_ONU', data=data_set, palette='Set2')
plt.title('Distribuição de Classificação do IDHM por Estado (ONU)')
plt.xlabel('Estado')
plt.ylabel('Número de Municípios')
plt.xticks(rotation=45)
plt.show()

data_set['Regiao'] = data_set['Estado'].map(regioes_brasil)
media_idhm_por_regiao = data_set.groupby('Regiao')['IDHM'].mean()

print("\nMédia do IDHM por Região:")
print(media_idhm_por_regiao)

plt.figure(figsize=(10,6))
sns.barplot(x=media_idhm_por_regiao.index, y=media_idhm_por_regiao.values, palette='viridis')
plt.title('Média do IDHM por Região')
plt.xlabel('Região')
plt.ylabel('Média do IDHM')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,6))
sns.countplot(x='Regiao', hue='Classificacao_ONU', data=data_set, palette='Set2')
plt.title('Distribuição de Classificação do IDHM por Região (ONU)')
plt.xlabel('Região')
plt.ylabel('Número de Municípios')
plt.xticks(rotation=45)
plt.show()

"""## Questão D"""

data_set['Regiao'] = data_set['Estado'].map(regioes_brasil)

plt.figure(figsize=(10,6))
sns.boxplot(x='Regiao', y='IDHM_Educacao', data=data_set, palette='Set2')
plt.title('Boxplot do IDHM_Educacao por Região')
plt.xlabel('Região')
plt.ylabel('IDHM_Educacao')
plt.xticks(rotation=45)
plt.show()

"""- Assim como no gráfico anterior que mostra a média do IDHM por região, o boxplot revela que regiões como o Nordeste e Norte têm uma distribuição de IDHM_Educacao mais baixa em comparação com o Centro-Oeste e Sul, que tendem a ter valores mais altos.

- O boxplot revela mais sobre a variabilidade dentro de cada região. Por exemplo, enquanto a média de IDHM_Educacao pode ser parecida em algumas regiões, o boxplot mostra se há uma maior disparidade em termos de acesso à educação dentro de uma mesma região. Isso pode indicar que algumas regiões têm municípios com educação de alta qualidade, mas também com uma significativa quantidade de municípios com baixos índices educacionais.

## Questão E
"""

media_idhm_educacao_por_regiao = data_set.groupby('Regiao')['IDHM_Educacao'].mean()

regiao_menor_media_educacao = media_idhm_educacao_por_regiao.idxmin()
print(f"A região com a menor média de IDHM_Educacao é: {regiao_menor_media_educacao}")

municipios_regiao_menor_media = data_set[data_set['Regiao'] == regiao_menor_media_educacao]

terceiro_quartil_ibge_1_4 = data_set['IBGE_1-4'].quantile(0.75)
print(f"O 3º quartil nacional para IBGE_1-4 é: {terceiro_quartil_ibge_1_4}")

municipios_acima_terceiro_quartil = municipios_regiao_menor_media[municipios_regiao_menor_media['IBGE_1-4'] > terceiro_quartil_ibge_1_4]

print("\nMunicípios acima do 3º quartil nacional para IBGE_1-4:")
print(municipios_acima_terceiro_quartil[['Município', 'Estado', 'IBGE_1-4', 'IDHM_Educacao']])

"""Essa analise indica áreas (principalmentre regão Nordeste) onde é necessário um foco especial em políticas de educação infantil, dada a importância da faixa etária para o desenvolvimento futuro.

## Questão F
"""

primeiro_quartil_comp_p = data_set['COMP_P'].quantile(0.25)
print(f"O 1º quartil nacional para COMP_P (empresas de educação) é: {primeiro_quartil_comp_p}")

municipios_primeiro_quartil = data_set[data_set['COMP_P'] <= primeiro_quartil_comp_p]

print("\nOs 10 primeiros municípios no 1º quartil nacional para COMP_P (menos empresas de educação) com sua respectiva região:")
print(municipios_primeiro_quartil[['Município', 'Estado', 'Regiao', 'COMP_P', 'IDHM_Educacao']].head(10))

plt.figure(figsize=(10,6))
sns.countplot(x='Regiao', data=municipios_primeiro_quartil, palette='Set3')
plt.title('Quantidade de Municípios no 1º Quartil para COMP_P (Empresas de Educação) por Região')
plt.xlabel('Região')
plt.ylabel('Número de Municípios')
plt.xticks(rotation=45)
plt.show()

"""## Questão G

A ordem de priorização para investimento em educação, com base nas análises, é a seguinte:

- Nordeste e Norte: Prioridade máxima, pois apresentam baixos índices de IDHM_Educacao e poucas empresas educacionais (COMP_P). Estados como Bahia (BA), Piauí (PI), Maranhão (MA) e Pará (PA) devem ser o foco.

- Municípios com alta concentração de crianças (1-4 anos): Investir em cidades dessas regiões com grande número de crianças e baixo IDHM_Educacao, principalmente no Nordeste e Norte.

- Municípios com grandes disparidades internas: Áreas com grande variabilidade no IDHM_Educacao, como no Centro-Oeste e Sudeste, precisam de equilíbrio nos investimentos.

- Municípios com baixo desenvolvimento geral: Cidades com baixo IDHM geral nas mesmas regiões devem receber atenção integrada (educação e qualidade de vida).
"""